-- local g = vim.g

-- return {
--   {
--     'lervag/vimtex',
--     config = function()
--       g.tex_flavor = 'latex'
--       g.vimtex_compiler_method = "latexmk"
--       g.vimtex_compiler_latexmk = {
--         callback = 1,
--         continuous = 1,
--         executable = "latexmk",
--         options = {
--           "-shell-escape",
--           "-verbose",
--           "-file-line-error",
--           "-synctex=1",
--           "-interaction=nonstopmode",
--         },
--       }
--       g.vimtex_imaps_enabled = 0
--       g.vimtex_view_method = 'zathura'
--       g.vimtex_quickfix_mode = 0
--     end,
--     ft = {
--       'tex',
--     },
--   },
--   {
--     'SirVer/ultisnips',
--     config = function()
--       g.UltiSnipsExpandTrigger = '<tab>'
--       g.UltiSnipsJumpForwardTrigger = '<tab>'
--       g.UltiSnipsJumpBackwardTrigger = '<s-tab>'
--     end,
--   },
--   {
--     'KeitaNakamura/tex-conceal.vim',
--     config = function()
--       vim.opt.conceallevel = 1
--       g.tex_conceal = 'abdmg'
--       vim.cmd('hi Conceal ctermbg=none')
--     end,
--   }
-- }

return {}
