#!/usr/bin/env zsh

source "$HOME/.config/sketchybar/colors.sh"

SKETCHYBAR_CONFIG="$HOME/.config/sketchybar"
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"
FONT_FACE="SauceCodePro Nerd Font"

sketchybar	--bar \
                height=32 \
                blur_radius=0 \
                position=top \
                sticky=on \
                padding_left=13 \
                padding_right=13 \
                display=main \
                color=$BAR_COLOR

sketchybar	--default \
                updates=when_shown \
                background.color=$BASE \
                background.padding_left=2 \
                background.padding_right=2 \
                background.corner_radius=5 \
                background.height=24 \
                icon.color=$ICON_COLOR \
                icon.font="$FONT_FACE:Bold:17.0" \
                icon.padding_left=8 \
                icon.padding_right=7 \
                label.font="$FONT_FACE:Bold:12.0" \
                label.color=$LABEL_COLOR \
                label.padding_left=0 \
                label.padding_right=7 \
                label.y_offset=1

sketchybar	--add	item current_space left \
            --set	current_space \
                        background.color=$MAUVE \
                        background.padding_right=5 \
                        icon.font="$FONT_FACE:Bold:13.0" \
                        icon.color=$BASE \
                        label.drawing=off \
                        script="$PLUGIN_DIR/current_space.sh" \
            --subscribe current_space space_change mouse.clicked

sketchybar 	--add item front_app left \
            --set   front_app \
                          background.color=$TEAL \
                          background.padding_left=0 \
                          background.padding_right=0 \
                          icon.y_offset=1 \
                          icon.color=$BASE \
                          label.drawing=no \
                          script="$PLUGIN_DIR/front_app.sh" \
          	--add item front_app.separator left \
            --set   front_app.separator \
                          icon= \
                          background.padding_left=-3 \
                          icon.y_offset=0 \
                          icon.font="$FONT_FACE:Bold:19.0" \
                          icon.color=$TEAL \
                          icon.padding_left=0 \
                          icon.padding_right=0 \
                          label.drawing=no \
          --add item front_app.name left \
          --set front_app.name \
                    icon.drawing=off \
                    label="Hello" \
                    label.drawing=yes

sketchybar  --add   bracket front_app_bracket \
                    front_app \
                    front_app.separator \
                    front_app.name \
            --subscribe	front_app front_app_switched \

sketchybar	--add	item weather q \
            --set	weather \
                        background.padding_right=-7 \
                    	icon= \
                    	icon.color=$FLAMINGO \
                        icon.font="$FONT_FACE:Bold:15.0" \
                    	update_freq=1800 \
                    	script="$PLUGIN_DIR/weather.sh" \
            --subscribe weather system_woke mouse.clicked

SPOTIFY_EVENT="com.spotify.client.PlaybackStateChanged"
sketchybar  --add   event spotify_change $SPOTIFY_EVENT \
            --add   item spotify e \
            --set   spotify \
                        background.padding_left=-5 \
                        icon= \
                    	icon.font="$FONT_FACE:Bold:20.0" \
                    	icon.y_offset=1 \
                        label.drawing=off \
                    	label.padding_left=2 \
                        script="$PLUGIN_DIR/spotify.sh" \
            --subscribe spotify spotify_change mouse.clicked

sketchybar  --add   item clock right \
            --set   clock \
                        icon= \
                        icon.y_offset=1 \
                        icon.color=$RED \
                        update_freq=10 \
                        script="$PLUGIN_DIR/clock.sh"

sketchybar  --add   item battery right \
            --set   battery \
                        update_freq=1 \
                        script="$PLUGIN_DIR/battery.sh" \
           --subscribe battery system_woke

BLUETOOTH_EVENT="com.apple.BluetoothDevicePairingChangedNotification"
sketchybar  --add   event   bluetooth_change $BLUETOOTH_EVENT \
            --add   item    bluetooth right \
            --set   bluetooth \
                        icon.y_offset=1 \
                        icon.padding_left=10 \
                        icon.padding_right=10 \
                        label.drawing=no \
                        script="$PLUGIN_DIR/bluetooth.sh" \
           --subscribe bluetooth bluetooth_change mouse.clicked

sketchybar	--add	item	volume right \
            --set volume \
                      icon.y_offset=1 \
                      icon.color=$FLAMINGO \
                      label.drawing=no \
                      script="$PLUGIN_DIR/volume.sh" \
           --subscribe volume volume_change mouse.clicked

source "$HOME/.config/sketchybar/notch_adjust.sh"

##### Finalizing Setup #####
sketchybar --update
sketchybar --trigger space_change
